#! /bin/sh

sxhkd &

if [ "$HDMI_STATUS" = connected ]
then
	bspc monitor eDP1 -d "1. desktop" "2. code" "3. browse" "4. explore"
	bspc monitor HDMI1 -d "5. music " "6. study" " 7. chat" "8. video" 
else
	bspc monitor eDP1 -d "1. desktop" "2. code" "3. browse" "4. explore" "5. music" "6. study" "7. chat" "8. video"
fi

bspc config normal_border_color   "#666666"
bspc config focused_border_color  "#9FA1B3"
bspc config urgent_border_color   "#9FA1B3"

bspc config window_gap           10
bspc config top_padding          15
bspc config bottom_padding       15
bspc config left_padding         0
bspc config right_padding        0
bspc config border_width         0
bspc config split_ratio          0.5

bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_by_distance       false
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config click_to_focus          false
bspc config center_pseudo_tiled     true

# Workspace assignments
bspc rule -a Nautilus desktop='^4'
bspc rule -a Firefox  desktop='^3'
bspc rule -a Chromium desktop='^3'
bspc rule -a pomodone desktop='^1'
bspc rule -a Gitter   desktop='^7'
bspc rule -a Evince   desktop='^6'
bspc rule -a Subl3     desktop="^2"
bspc rule -a scratchpad sticky=on state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google Chromedesktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrdb ~/.Xresources
numlockx &
xsetroot -cursor_name left_ptr
setxkbmap -layout us,ru -option grp:caps_toggle,grp_led:caps
feh --bg-fill ~/Pictures/wallpaper01.jpg

~/.config/scripts/launchbar &
